# Generated by Django 4.2 on 2024-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpreference',
            name='num_days',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
